### ISSUE TITLE
the code alignment in train_baseline.py is so weird.....

### ISSUE THREAD

**Issue by ZJX-CV** [wl-zhao/DIML#1]
兄弟 好奇怪的代码对齐方式啊.... 看的我难受

**Comment by wl-zhao** [comment]
Hi, the code is based on [RevisitingDML](https://github.com/Confusezius/Revisiting_Deep_Metric_Learning_PyTorch). We agree the code is not pretty enough and we will spare some time to make it better (perhaps after CVPR)
