### ISSUE TITLE
Einsum order bug?

### ISSUE THREAD

**Issue by cazhang** [wl-zhao/DIML#6]
In line 24 of utilities/diml.py
cm, ncs->nsm 

While in line 73 of criteria/margin_diml.py, it is
bcs, bcm->bsm 

I think the former one is correct,
Is this a bug that potentially make your results when training worse?

**Comment by cazhang** [comment]
@wl-zhao could you help me with this question?

**Comment by wl-zhao** [comment]
Thanks for your help! I think you are right and fixing the bug perhaps will make the training better. I will conduct experiments later and update the results.
